# Generated by Django 3.0.6 on 2020-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200607_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(default=-1),
        ),
    ]
