# Generated by Django 3.0.6 on 2020-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groupid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='', max_length=100),
        ),
    ]
