# Generated by Django 3.0.6 on 2020-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200607_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
